coverage:
  status:
    project:
      default:
        target: 95%          # target coverage (fail if below)
        threshold: 1%        # allow 1% drop from main before fail
    patch:
      default:
        target: 95%          # minimal patch coverage
        threshold: 1%        # allow 1% drop
