repos:
  - repo: local
    hooks:
      - id: csharpier
        name: Run CSharpier on C# files
        entry: dotnet 
        args: [tool, run, csharpier, format]
        language: system
        description: CSharpier is an opinionated C# formatter inspired by Prettier.