// <auto-generated/>
#pragma warning disable
file static class AssemblyLoader20fe026d2d6844a28457afb52ccce168
{
	[global::System.Runtime.CompilerServices.ModuleInitializer]
	public static void Initialize()
	{
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("AutoFixture, Version=4.18.0.0, Culture=neutral, PublicKeyToken=b24654c590009d4f"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("Fare, Version=2.1.0.0, Culture=neutral, PublicKeyToken=ea68d375bf33a7c8"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("AwesomeAssertions, Version=9.1.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("Bogus, Version=35.6.3.0, Culture=neutral, PublicKeyToken=fa1bb3f3f218129a"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("CsvHelper, Version=33.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("Dameng.Protobuf.Extension, Version=999.999.999.0, Culture=neutral, PublicKeyToken=null"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("Google.Protobuf, Version=3.32.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("EnumerableAsyncProcessor, Version=2.1.0.0, Culture=neutral, PublicKeyToken=7a7adb9c614908c9"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("TUnit.Assertions, Version=0.24.0.0, Culture=neutral, PublicKeyToken=b8d4030011dbd70c"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("TUnit.Core, Version=0.24.0.0, Culture=neutral, PublicKeyToken=b8d4030011dbd70c"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("TUnit, Version=0.24.0.0, Culture=neutral, PublicKeyToken=b8d4030011dbd70c"));
		global::TUnit.Core.SourceRegistrar.RegisterAssembly(() => global::System.Reflection.Assembly.Load("TUnit.Engine, Version=0.24.0.0, Culture=neutral, PublicKeyToken=b8d4030011dbd70c"));
	}
}
