using CSharpier.Core.CSharp;
using Google.Protobuf.Reflection;
using LightProto.ProtoGen;
using ProtoBuf.Reflection;

namespace LightProto.ProtoGen.Tests;

/// <summary>
/// Tests for <see cref="LightProtoCSharpGenerator"/>.
///
/// Each code-generation test asserts that the full generated file, once formatted by CSharpier,
/// is identical to the expected file string, also formatted by CSharpier.
/// Because CSharpier produces deterministic output for semantically identical code, trivial
/// whitespace differences in the expected string are automatically normalised.
/// </summary>
public class LightProtoCSharpGeneratorTests
{
    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Parses <paramref name="protoSchema"/> and generates C# code with the given options.
    /// </summary>
    private static string Generate(string protoSchema, string? ns = null, GeneratorOptions? opts = null)
    {
        var set = new FileDescriptorSet();
        using (var reader = new System.IO.StringReader(protoSchema))
        {
            set.Add("test.proto", source: reader);
        }
        set.Process();
        var errors = set.GetErrors();
        if (errors.Length > 0)
            throw new InvalidOperationException(string.Join(Environment.NewLine, errors.Select(e => e.ToString())));

        var file = set.Files.First();
        return new LightProtoCSharpGenerator(opts).Generate(file, ns);
    }

    /// <summary>
    /// Formats a C# code string with CSharpier, producing deterministic output.
    /// </summary>
    private static async Task<string> FmtAsync(string code)
    {
        var result = await CSharpFormatter.FormatAsync(code, new CSharpier.Core.CodeFormatterOptions());
        return result.Code ?? code;
    }

    /// <summary>
    /// Asserts that <paramref name="generatedCode"/> and <paramref name="expectedCode"/>,
    /// after being formatted by CSharpier, are identical strings.
    /// </summary>
    private static async Task AssertCodeEqual(string generatedCode, string expectedCode)
    {
        // TrimEnd() normalises trailing-newline differences only (raw string literals in C#
        // don't include a final newline, but CSharpier always appends one to formatted files).
        var fmtGenerated = (await FmtAsync(generatedCode)).TrimEnd();
        var fmtExpected = (await FmtAsync(expectedCode)).TrimEnd();
        await Assert.That(fmtGenerated).IsEqualTo(fmtExpected);
    }

    // -------------------------------------------------------------------------
    // Baseline: attributes and class declaration
    // -------------------------------------------------------------------------

    [Test]
    public async Task GeneratesProtoContractAttribute()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message MyMessage { int32 id = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class MyMessage
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? Id { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task GeneratesProtoMemberTagNumbers()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { string first = 1; int32 second = 42; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public string? First { get; set; }

                    [global::LightProto.ProtoMember(42)]
                    public int? Second { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // Scalar types – nullable by default
    // -------------------------------------------------------------------------

    [Test]
    public async Task DefaultModeAllScalarsAreNullable()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { int32 a=1; int64 b=2; uint32 c=3; uint64 d=4; bool e=5; float f=6; double g=7; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? A { get; set; }

                    [global::LightProto.ProtoMember(2)]
                    public long? B { get; set; }

                    [global::LightProto.ProtoMember(3)]
                    public uint? C { get; set; }

                    [global::LightProto.ProtoMember(4)]
                    public ulong? D { get; set; }

                    [global::LightProto.ProtoMember(5)]
                    public bool? E { get; set; }

                    [global::LightProto.ProtoMember(6)]
                    public float? F { get; set; }

                    [global::LightProto.ProtoMember(7)]
                    public double? G { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task DefaultModeStringIsNullable()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { string name = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public string? Name { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task DefaultModeBytesIsNullable()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { bytes data = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public byte[]? Data { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task DefaultModeEnumIsNullable()
    {
        var code = Generate(
            """
            syntax = "proto3";
            enum Color { RED = 0; GREEN = 1; }
            message Msg { Color color = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                public enum Color
                {
                    Red = 0,
                    Green = 1,
                }

                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public Color? Color { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task DefaultModeMessageRefIsNullable()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Inner { int32 x = 1; }
            message Outer { Inner child = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Inner
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? X { get; set; }
                }

                [global::LightProto.ProtoContract]
                public partial class Outer
                {
                    [global::LightProto.ProtoMember(1)]
                    public Inner? Child { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // Strict-optional mode
    // -------------------------------------------------------------------------

    [Test]
    public async Task StrictOptionalMode_NonOptionalScalarsAreNotNullable()
    {
        var opts = new GeneratorOptions { StrictOptional = true };
        var code = Generate(
            """
            syntax = "proto3";
            message Msg {
              int32          mandatory = 1;
              optional int32 explicitly_optional = 2;
            }
            """,
            "TestNs",
            opts
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public int Mandatory { get; set; }

                    [global::LightProto.ProtoMember(2)]
                    public int? ExplicitlyOptional { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task StrictOptionalMode_NonOptionalStringHasEmptyDefault()
    {
        var opts = new GeneratorOptions { StrictOptional = true };
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { string name = 1; }
            """,
            "TestNs",
            opts
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public string Name { get; set; } = string.Empty;
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task StrictOptionalMode_NonOptionalBytesHasEmptyDefault()
    {
        var opts = new GeneratorOptions { StrictOptional = true };
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { bytes data = 1; }
            """,
            "TestNs",
            opts
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public byte[] Data { get; set; } = global::System.Array.Empty<byte>();
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // Repeated and map fields
    // -------------------------------------------------------------------------

    [Test]
    public async Task RepeatedFieldIsListNotNullable()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { repeated string tags = 1; repeated int32 ids = 2; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public global::System.Collections.Generic.List<string> Tags { get; set; } = new();

                    [global::LightProto.ProtoMember(2)]
                    public global::System.Collections.Generic.List<int> Ids { get; set; } = new();
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task MapFieldIsDictionaryWithProtoMap()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { map<string, int32> counts = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    [global::LightProto.ProtoMap]
                    public global::System.Collections.Generic.Dictionary<string, int> Counts { get; set; } = new();
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task MapFieldWithDataFormats()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { map<sfixed32, sint64> fancy = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    [global::LightProto.ProtoMap(KeyFormat = global::LightProto.DataFormat.FixedSize, ValueFormat = global::LightProto.DataFormat.ZigZag)]
                    public global::System.Collections.Generic.Dictionary<int, long> Fancy { get; set; } = new();
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // DataFormat attributes
    // -------------------------------------------------------------------------

    [Test]
    public async Task ZigZagDataFormatForSint()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { sint32 a = 1; sint64 b = 2; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1, DataFormat = global::LightProto.DataFormat.ZigZag)]
                    public int? A { get; set; }

                    [global::LightProto.ProtoMember(2, DataFormat = global::LightProto.DataFormat.ZigZag)]
                    public long? B { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task FixedSizeDataFormatForFixed()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { fixed32 a = 1; fixed64 b = 2; sfixed32 c = 3; sfixed64 d = 4; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1, DataFormat = global::LightProto.DataFormat.FixedSize)]
                    public uint? A { get; set; }

                    [global::LightProto.ProtoMember(2, DataFormat = global::LightProto.DataFormat.FixedSize)]
                    public ulong? B { get; set; }

                    [global::LightProto.ProtoMember(3, DataFormat = global::LightProto.DataFormat.FixedSize)]
                    public int? C { get; set; }

                    [global::LightProto.ProtoMember(4, DataFormat = global::LightProto.DataFormat.FixedSize)]
                    public long? D { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // Enum generation
    // -------------------------------------------------------------------------

    [Test]
    public async Task GeneratesTopLevelEnum()
    {
        var code = Generate(
            """
            syntax = "proto3";
            enum Status { UNKNOWN = 0; ACTIVE = 1; DELETED = 2; }
            message Msg { Status state = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                public enum Status
                {
                    Unknown = 0,
                    Active = 1,
                    Deleted = 2,
                }

                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public Status? State { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // Nested messages
    // -------------------------------------------------------------------------

    [Test]
    public async Task GeneratesNestedMessage()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Outer {
              message Inner { int32 value = 1; }
              Inner child = 1;
            }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Outer
                {
                    [global::LightProto.ProtoContract]
                    public partial class Inner
                    {
                        [global::LightProto.ProtoMember(1)]
                        public int? Value { get; set; }
                    }

                    [global::LightProto.ProtoMember(1)]
                    public Outer.Inner? Child { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // Namespace handling
    // -------------------------------------------------------------------------

    [Test]
    public async Task UsesProtoFileNamespaceOption()
    {
        var code = Generate(
            """
            syntax = "proto3";
            option csharp_namespace = "My.App.Models";
            message Msg { string name = 1; }
            """
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace My.App.Models
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public string? Name { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task OverrideNamespaceTakesPrecedence()
    {
        var code = Generate(
            """
            syntax = "proto3";
            option csharp_namespace = "OriginalNs";
            message Msg { string name = 1; }
            """,
            "OverriddenNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace OverriddenNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public string? Name { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // struct / record / record struct
    // -------------------------------------------------------------------------

    [Test]
    public async Task UseStructOptionGeneratesPartialStruct()
    {
        var opts = new GeneratorOptions { UseStruct = true };
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { int32 x = 1; }
            """,
            "TestNs",
            opts
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial struct Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? X { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task UseRecordOptionGeneratesPartialRecord()
    {
        var opts = new GeneratorOptions { UseRecord = true };
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { int32 x = 1; }
            """,
            "TestNs",
            opts
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial record Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? X { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task UseRecordAndStructOptionGeneratesPartialRecordStruct()
    {
        var opts = new GeneratorOptions { UseRecord = true, UseStruct = true };
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { int32 x = 1; }
            """,
            "TestNs",
            opts
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial record struct Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? X { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task DefaultOptionGeneratesPartialClass()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg { int32 x = 1; }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? X { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // oneof handling
    // -------------------------------------------------------------------------

    [Test]
    public async Task OneofWithAllMessageFieldsGeneratesProtoInclude()
    {
        // UseProtoIncludeForOneof must be explicitly set; default is false.
        var opts = new GeneratorOptions { UseProtoIncludeForOneof = true };
        var code = Generate(
            """
            syntax = "proto3";
            message Dog  { string breed = 1; }
            message Cat  { bool indoor = 1; }
            message Animal {
              oneof kind {
                Dog dog = 1;
                Cat cat = 2;
              }
            }
            """,
            "TestNs",
            opts
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Dog
                {
                    [global::LightProto.ProtoMember(1)]
                    public string? Breed { get; set; }
                }

                [global::LightProto.ProtoContract]
                public partial class Cat
                {
                    [global::LightProto.ProtoMember(1)]
                    public bool? Indoor { get; set; }
                }

                [global::LightProto.ProtoContract]
                [global::LightProto.ProtoInclude(1, typeof(Dog))]
                [global::LightProto.ProtoInclude(2, typeof(Cat))]
                public partial class Animal
                {
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task OneofWithMixedTypesEmitsNullableProperties()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Msg {
              oneof mixed {
                string text = 1;
                int32  num  = 2;
              }
            }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Msg
                {
                    [global::LightProto.ProtoMember(1)]
                    public string? Text { get; set; }

                    [global::LightProto.ProtoMember(2)]
                    public int? Num { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task FieldsOutsideOneofAreNotAffectedByOneofPromotion()
    {
        // Default mode: no ProtoInclude; all oneof fields emitted as nullable properties.
        var code = Generate(
            """
            syntax = "proto3";
            message Dog  { string breed = 1; }
            message Cat  { bool indoor = 1; }
            message Animal {
              string name = 3;
              oneof kind { Dog dog = 1; Cat cat = 2; }
            }
            """,
            "TestNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace TestNs
            {
                [global::LightProto.ProtoContract]
                public partial class Dog
                {
                    [global::LightProto.ProtoMember(1)]
                    public string? Breed { get; set; }
                }

                [global::LightProto.ProtoContract]
                public partial class Cat
                {
                    [global::LightProto.ProtoMember(1)]
                    public bool? Indoor { get; set; }
                }

                [global::LightProto.ProtoContract]
                public partial class Animal
                {
                    [global::LightProto.ProtoMember(3)]
                    public string? Name { get; set; }

                    [global::LightProto.ProtoMember(1)]
                    public Dog? Dog { get; set; }

                    [global::LightProto.ProtoMember(2)]
                    public Cat? Cat { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // CSharpier full-file formatted comparisons
    // -------------------------------------------------------------------------

    [Test]
    public async Task FormattedOutputMatchesExpectedForSimpleMessage()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Person { int32 id = 1; string name = 2; }
            """,
            "MyNs",
            new GeneratorOptions { StrictOptional = true }
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace MyNs
            {
                [global::LightProto.ProtoContract]
                public partial class Person
                {
                    [global::LightProto.ProtoMember(1)]
                    public int Id { get; set; }

                    [global::LightProto.ProtoMember(2)]
                    public string Name { get; set; } = string.Empty;
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    [Test]
    public async Task FormattedOutputMatchesExpectedForNullableDefaultMessage()
    {
        var code = Generate(
            """
            syntax = "proto3";
            message Pt { int32 x = 1; int32 y = 2; }
            """,
            "MyNs"
        );

        const string expected = """
            // <auto-generated/>
            // This file was generated by lightproto-gen. Do not edit manually.
            #nullable enable

            namespace MyNs
            {
                [global::LightProto.ProtoContract]
                public partial class Pt
                {
                    [global::LightProto.ProtoMember(1)]
                    public int? X { get; set; }

                    [global::LightProto.ProtoMember(2)]
                    public int? Y { get; set; }
                }
            }
            """;

        await AssertCodeEqual(code, expected);
    }

    // -------------------------------------------------------------------------
    // Name conversion
    // -------------------------------------------------------------------------

    [Test]
    public async Task ToPascalCase_ConvertsSnakeCase()
    {
        await Assert.That(LightProtoCSharpGenerator.ToPascalCase("my_field_name")).IsEqualTo("MyFieldName");
        await Assert.That(LightProtoCSharpGenerator.ToPascalCase("order_id")).IsEqualTo("OrderId");
        await Assert.That(LightProtoCSharpGenerator.ToPascalCase("simple")).IsEqualTo("Simple");
        await Assert.That(LightProtoCSharpGenerator.ToPascalCase("ALL_CAPS")).IsEqualTo("AllCaps");
    }
}
