using Google.Protobuf.Reflection;
using ProtoBuf.Reflection;

namespace LightProto.ProtoGen;

/// <summary>
/// Generates LightProto [ProtoContract] C# classes from a parsed proto FileDescriptorSet.
/// </summary>
internal sealed class LightProtoCSharpGenerator
{
    // Maps proto scalar types to their C# type names and optional DataFormat
    private static readonly Dictionary<FieldDescriptorProto.Type, (string CsType, string? DataFormat)> ScalarTypeMap = new()
    {
        [FieldDescriptorProto.Type.TypeDouble] = ("double", null),
        [FieldDescriptorProto.Type.TypeFloat] = ("float", null),
        [FieldDescriptorProto.Type.TypeInt32] = ("int", null),
        [FieldDescriptorProto.Type.TypeInt64] = ("long", null),
        [FieldDescriptorProto.Type.TypeUint32] = ("uint", null),
        [FieldDescriptorProto.Type.TypeUint64] = ("ulong", null),
        [FieldDescriptorProto.Type.TypeSint32] = ("int", "DataFormat.ZigZag"),
        [FieldDescriptorProto.Type.TypeSint64] = ("long", "DataFormat.ZigZag"),
        [FieldDescriptorProto.Type.TypeFixed32] = ("uint", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeFixed64] = ("ulong", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeSfixed32] = ("int", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeSfixed64] = ("long", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeBool] = ("bool", null),
        [FieldDescriptorProto.Type.TypeString] = ("string", null),
        [FieldDescriptorProto.Type.TypeBytes] = ("byte[]", null),
    };

    private readonly string _indent = "    ";
    private readonly GeneratorOptions _options;

    public LightProtoCSharpGenerator(GeneratorOptions? options = null)
    {
        _options = options ?? new GeneratorOptions();
    }

    /// <summary>
    /// Generates C# source code for all messages and enums in the given file descriptor.
    /// </summary>
    public string Generate(FileDescriptorProto file, string? overrideNamespace = null)
    {
        var ns =
            overrideNamespace ?? file.Options?.CsharpNamespace ?? ToPascalCase(Path.GetFileNameWithoutExtension(file.Name ?? "Generated"));

        // The proto package (e.g. "my.pkg") is used to strip package-qualified type name
        // prefixes so that ".my.pkg.Foo" resolves to the emitted C# class "Foo", not "My.Pkg.Foo".
        var package = file.Package ?? "";

        // Build a lookup of all map-entry nested types for the whole file.
        // Keys are relative to the file root (no package prefix), e.g. ".Msg.EntryName".
        var mapEntries = BuildMapEntryLookup(file.MessageTypes);

        // When emitting [ProtoInclude], the referenced types must inherit from the declaring type.
        // Pre-compute a mapping: emitted C# type name → base C# type name.
        var protoIncludeInheritance =
            _options.OneofHandling == OneofHandling.ProtoInclude
                ? BuildProtoIncludeInheritance(file.MessageTypes, mapEntries, package)
                : new Dictionary<string, string>();

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file was generated by lightproto-gen. Do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");

        bool firstItem = true;

        // Top-level enums
        foreach (var enumType in file.EnumTypes)
        {
            if (!firstItem)
                sb.AppendLine();
            firstItem = false;
            AppendEnum(sb, enumType, _indent);
        }

        // Top-level messages
        foreach (var message in file.MessageTypes)
        {
            if (!firstItem)
                sb.AppendLine();
            firstItem = false;
            AppendMessage(sb, message, mapEntries, package, protoIncludeInheritance, _indent, "");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Enum generation
    // -------------------------------------------------------------------------

    private static void AppendEnum(System.Text.StringBuilder sb, EnumDescriptorProto enumType, string indent)
    {
        sb.AppendLine($"{indent}public enum {ToPascalCase(enumType.Name)}");
        sb.AppendLine($"{indent}{{");
        foreach (var value in enumType.Values)
        {
            sb.AppendLine($"{indent}    {ToPascalCase(value.Name)} = {value.Number},");
        }
        sb.AppendLine($"{indent}}}");
    }

    // -------------------------------------------------------------------------
    // Message generation
    // -------------------------------------------------------------------------

    private void AppendMessage(
        System.Text.StringBuilder sb,
        DescriptorProto message,
        Dictionary<string, DescriptorProto> mapEntries,
        string package,
        Dictionary<string, string> protoIncludeInheritance,
        string indent,
        string messagePrefix
    )
    {
        // Skip map-entry synthetic messages (they are handled inline as Dictionary<K,V>)
        if (message.Options?.MapEntry == true)
            return;

        // Add nested map entries from this message to the lookup
        var localMapEntries = new Dictionary<string, DescriptorProto>(mapEntries);
        foreach (var nested in message.NestedTypes)
        {
            if (nested.Options?.MapEntry == true)
                localMapEntries[$".{message.Name}.{nested.Name}"] = nested;
        }

        // Collect oneof groups whose fields are all message-typed → emit [ProtoInclude]
        // (only when OneofHandling == ProtoInclude; default is to emit as nullable properties)
        var protoIncludes =
            _options.OneofHandling == OneofHandling.ProtoInclude ? CollectProtoIncludes(message, localMapEntries, package) : [];

        sb.AppendLine($"{indent}[global::LightProto.ProtoContract]");

        foreach (var (tag, typeName) in protoIncludes)
        {
            sb.AppendLine($"{indent}[global::LightProto.ProtoInclude({tag}, typeof({typeName}))]");
        }

        // The full dotted C# name used for the ProtoInclude inheritance lookup,
        // e.g. "Outer.Inner" for a nested message or just "Dog" for a top-level one.
        var csMessageName = ToPascalCase(message.Name);
        var fullCsName = string.IsNullOrEmpty(messagePrefix) ? csMessageName : $"{messagePrefix}.{csMessageName}";

        // Emit `: BaseType` when this message is a known sub-type of a ProtoInclude parent.
        if (protoIncludeInheritance.TryGetValue(fullCsName, out var baseTypeName))
            sb.AppendLine($"{indent}public partial {_options.TypeKeyword} {csMessageName} : {baseTypeName}");
        else
            sb.AppendLine($"{indent}public partial {_options.TypeKeyword} {csMessageName}");

        sb.AppendLine($"{indent}{{");

        var innerIndent = indent + _indent;

        // Nested enums
        foreach (var enumType in message.EnumTypes)
        {
            AppendEnum(sb, enumType, innerIndent);
            sb.AppendLine();
        }

        // Nested messages (non-map-entry)
        foreach (var nested in message.NestedTypes)
        {
            if (nested.Options?.MapEntry == true)
                continue;
            AppendMessage(sb, nested, localMapEntries, package, protoIncludeInheritance, innerIndent, fullCsName);
            sb.AppendLine();
        }

        // Build the set of oneof field indices that are covered by ProtoInclude
        // (empty when OneofHandling != ProtoInclude, so all fields are emitted)
        var protoIncludeOneofIndices =
            _options.OneofHandling == OneofHandling.ProtoInclude
                ? GetProtoIncludeOneofIndices(message, localMapEntries, package)
                : new HashSet<int>();

        // Fields (skip oneof fields that were promoted to ProtoInclude)
        bool firstField = true;
        foreach (var field in message.Fields)
        {
            // If this field belongs to a oneof that was fully promoted to ProtoInclude, skip it
            if (FieldIsInOneof(field) && protoIncludeOneofIndices.Contains(field.OneofIndex))
                continue;

            if (!firstField)
                sb.AppendLine();
            firstField = false;
            AppendField(sb, field, localMapEntries, package, innerIndent);
        }

        sb.AppendLine($"{indent}}}");
    }

    /// <summary>
    /// Pre-computes a mapping from emitted C# type name to its base C# type name for all
    /// message types that appear as [ProtoInclude] sub-types in message-only oneof groups.
    /// Keys use the full dotted path relative to the file (e.g. "Dog" or "Outer.Inner").
    /// </summary>
    private static Dictionary<string, string> BuildProtoIncludeInheritance(
        IList<DescriptorProto> messages,
        Dictionary<string, DescriptorProto> mapEntries,
        string package
    )
    {
        var result = new Dictionary<string, string>();
        CollectProtoIncludeInheritance(messages, mapEntries, package, "", result);
        return result;
    }

    private static void CollectProtoIncludeInheritance(
        IList<DescriptorProto> messages,
        Dictionary<string, DescriptorProto> mapEntries,
        string package,
        string currentPrefix,
        Dictionary<string, string> result
    )
    {
        foreach (var message in messages)
        {
            var csMessageName = ToPascalCase(message.Name);
            var fullCsName = string.IsNullOrEmpty(currentPrefix) ? csMessageName : $"{currentPrefix}.{csMessageName}";

            for (int i = 0; i < message.OneofDecls.Count; i++)
            {
                var oneofFields = message.Fields.Where(f => FieldIsInOneof(f) && f.OneofIndex == i).ToList();
                if (oneofFields.Count == 0 || !oneofFields.All(f => IsMessageType(f, mapEntries, package)))
                    continue;

                foreach (var field in oneofFields)
                {
                    var subCsName = ResolveTypeCsName(field.TypeName ?? "", package);
                    result.TryAdd(subCsName, csMessageName);
                }
            }

            // Recurse into nested messages
            var localMapEntries = new Dictionary<string, DescriptorProto>(mapEntries);
            foreach (var nested in message.NestedTypes)
            {
                if (nested.Options?.MapEntry == true)
                    localMapEntries[$".{message.Name}.{nested.Name}"] = nested;
            }
            CollectProtoIncludeInheritance(
                message.NestedTypes.Where(n => n.Options?.MapEntry != true).ToList(),
                localMapEntries,
                package,
                fullCsName,
                result
            );
        }
    }

    /// <summary>
    /// Returns a set of oneof group indices where all fields are message-typed
    /// and thus promoted to [ProtoInclude].
    /// </summary>
    private static HashSet<int> GetProtoIncludeOneofIndices(
        DescriptorProto message,
        Dictionary<string, DescriptorProto> mapEntries,
        string package
    )
    {
        var result = new HashSet<int>();
        for (int i = 0; i < message.OneofDecls.Count; i++)
        {
            var oneofFields = message.Fields.Where(f => FieldIsInOneof(f) && f.OneofIndex == i).ToList();
            if (oneofFields.Count > 0 && oneofFields.All(f => IsMessageType(f, mapEntries, package)))
                result.Add(i);
        }
        return result;
    }

    /// <summary>
    /// Collects (tag, CsTypeName) pairs for [ProtoInclude] attributes from message-only oneofs.
    /// </summary>
    private static List<(int Tag, string TypeName)> CollectProtoIncludes(
        DescriptorProto message,
        Dictionary<string, DescriptorProto> mapEntries,
        string package
    )
    {
        var result = new List<(int, string)>();
        for (int i = 0; i < message.OneofDecls.Count; i++)
        {
            var oneofFields = message.Fields.Where(f => FieldIsInOneof(f) && f.OneofIndex == i).ToList();
            if (oneofFields.Count == 0 || !oneofFields.All(f => IsMessageType(f, mapEntries, package)))
                continue;

            foreach (var field in oneofFields)
            {
                var typeName = ResolveTypeCsName(field.TypeName ?? "", package);
                result.Add((field.Number, typeName));
            }
        }
        return result;
    }

    /// <summary>
    /// Returns <see langword="true"/> if the field is a member of a oneof group.
    /// Uses the protobuf-net ShouldSerialize pattern since <see cref="FieldDescriptorProto.OneofIndex"/>
    /// defaults to 0 even for non-oneof fields.
    /// </summary>
    private static bool FieldIsInOneof(FieldDescriptorProto field)
    {
        // ShouldSerializeOneofIndex() returns true only when the oneof_index wire field was present
        return field.ShouldSerializeOneofIndex();
    }

    private static bool IsMessageType(FieldDescriptorProto field, Dictionary<string, DescriptorProto> mapEntries, string package)
    {
        // Must be a message type (not a map entry)
        if (field.type != FieldDescriptorProto.Type.TypeMessage)
            return false;
        // Exclude map-entry messages; normalize TypeName to match the package-free keys in mapEntries
        var normalizedTypeName = StripPackagePrefix(field.TypeName ?? "", package);
        if (mapEntries.ContainsKey(normalizedTypeName))
            return false;
        return true;
    }

    private void AppendField(
        System.Text.StringBuilder sb,
        FieldDescriptorProto field,
        Dictionary<string, DescriptorProto> mapEntries,
        string package,
        string indent
    )
    {
        // Detect map fields: repeated message whose type is a map-entry.
        // Normalize TypeName by stripping the package prefix so that it matches the
        // package-free keys that BuildMapEntryLookup stores (e.g. ".Msg.EntryName").
        var normalizedTypeName = StripPackagePrefix(field.TypeName ?? "", package);
        if (
            field.label == FieldDescriptorProto.Label.LabelRepeated
            && field.type == FieldDescriptorProto.Type.TypeMessage
            && mapEntries.TryGetValue(normalizedTypeName, out var mapEntry)
        )
        {
            AppendMapField(sb, field, mapEntry, package, indent);
            return;
        }

        bool isRepeated = field.label == FieldDescriptorProto.Label.LabelRepeated;
        var (csType, dataFormat) = ResolveType(field, mapEntries, package);

        // Determine if this field should be nullable
        bool makeNullable = !isRepeated && IsFieldNullable(field);

        // Build [ProtoMember] attribute
        var memberAttrArgs = $"{field.Number}";
        if (dataFormat != null)
            memberAttrArgs += $", DataFormat = global::LightProto.{dataFormat}";

        sb.AppendLine($"{indent}[global::LightProto.ProtoMember({memberAttrArgs})]");

        if (isRepeated)
        {
            sb.AppendLine(
                $"{indent}public global::System.Collections.Generic.List<{csType}> {ToPascalCase(field.Name)} {{ get; set; }} = new();"
            );
        }
        else if (makeNullable)
        {
            // Emit nullable type with null default
            var nullableType = MakeNullable(csType);
            sb.AppendLine($"{indent}public {nullableType} {ToPascalCase(field.Name)} {{ get; set; }}");
        }
        else
        {
            // Non-nullable: emit with appropriate default initializer
            if (csType == "string")
                sb.AppendLine($"{indent}public string {ToPascalCase(field.Name)} {{ get; set; }} = string.Empty;");
            else if (csType == "byte[]")
                sb.AppendLine($"{indent}public byte[] {ToPascalCase(field.Name)} {{ get; set; }} = global::System.Array.Empty<byte>();");
            else
                sb.AppendLine($"{indent}public {csType} {ToPascalCase(field.Name)} {{ get; set; }}");
        }
    }

    /// <summary>
    /// Determines whether a field should be emitted as a nullable type.
    /// </summary>
    private bool IsFieldNullable(FieldDescriptorProto field)
    {
        if (_options.Nullability == NullabilityMode.StrictOptional)
        {
            // Only fields explicitly declared with 'optional' in proto3 are nullable
            return field.Proto3Optional;
        }

        // Default: everything is nullable (proto3 all fields are optional on the wire)
        return true;
    }

    private static string MakeNullable(string csType)
    {
        // Reference types: string?, byte[]?, etc. (already end with ? for well-known nullable types)
        // Value types: int?, bool?, etc.
        if (csType.EndsWith("?"))
            return csType; // Already nullable (e.g., well-known type wrappers)
        if (csType.EndsWith("[]"))
            return csType + "?"; // byte[]?
        return csType + "?";
    }

    private static void AppendMapField(
        System.Text.StringBuilder sb,
        FieldDescriptorProto field,
        DescriptorProto mapEntry,
        string package,
        string indent
    )
    {
        var keyField = mapEntry.Fields.First(f => f.Name == "key");
        var valueField = mapEntry.Fields.First(f => f.Name == "value");

        var (keyCs, keyDataFormat) = ResolveType(keyField, new Dictionary<string, DescriptorProto>(), package);
        var (valueCs, valueDataFormat) = ResolveType(valueField, new Dictionary<string, DescriptorProto>(), package);

        // Build [ProtoMember] + [ProtoMap]
        sb.AppendLine($"{indent}[global::LightProto.ProtoMember({field.Number})]");
        var protoMapArgs = BuildProtoMapArgs(keyDataFormat, valueDataFormat);
        if (protoMapArgs.Length > 0)
            sb.AppendLine($"{indent}[global::LightProto.ProtoMap({protoMapArgs})]");
        else
            sb.AppendLine($"{indent}[global::LightProto.ProtoMap]");

        sb.AppendLine(
            $"{indent}public global::System.Collections.Generic.Dictionary<{keyCs}, {valueCs}> {ToPascalCase(field.Name)} {{ get; set; }} = new();"
        );
    }

    // -------------------------------------------------------------------------
    // Type resolution helpers
    // -------------------------------------------------------------------------

    private static (string CsType, string? DataFormat) ResolveType(
        FieldDescriptorProto field,
        Dictionary<string, DescriptorProto> mapEntries,
        string package
    )
    {
        if (ScalarTypeMap.TryGetValue(field.type, out var scalar))
            return scalar;

        if (field.type == FieldDescriptorProto.Type.TypeEnum || field.type == FieldDescriptorProto.Type.TypeMessage)
        {
            var rawTypeName = field.TypeName ?? "";

            // Well-known types are identified by their fully-qualified proto name (no stripping needed)
            var wellKnown = MapWellKnownType(rawTypeName.TrimStart('.'));
            if (wellKnown is not null)
                return (wellKnown, null);

            return (ResolveTypeCsName(rawTypeName, package), null);
        }

        return ("object", null);
    }

    /// <summary>
    /// Converts a fully-qualified proto type name (e.g. <c>.my.pkg.Outer.Inner</c>) to the
    /// emitted C# name (<c>Outer.Inner</c>) by stripping the file's package prefix and
    /// applying PascalCase to each remaining segment.
    /// </summary>
    private static string ResolveTypeCsName(string protoTypeName, string package)
    {
        var stripped = StripPackagePrefix(protoTypeName, package).TrimStart('.');
        if (string.IsNullOrEmpty(stripped))
            return "object";
        return string.Join(".", stripped.Split('.').Select(ToPascalCase));
    }

    /// <summary>
    /// Strips the proto <paramref name="package"/> prefix from a fully-qualified type name so
    /// that the remaining path is relative to the file root (e.g. <c>.my.pkg.Foo</c> →
    /// <c>.Foo</c> when package is <c>my.pkg</c>).
    /// </summary>
    private static string StripPackagePrefix(string typeName, string package)
    {
        if (string.IsNullOrEmpty(package))
            return typeName;
        var prefix = "." + package + ".";
        return typeName.StartsWith(prefix) ? "." + typeName[prefix.Length..] : typeName;
    }

    private static string? MapWellKnownType(string protoTypeName)
    {
        return protoTypeName switch
        {
            "google.protobuf.Timestamp" => "global::System.DateTime",
            "google.protobuf.Duration" => "global::System.TimeSpan",
            "google.protobuf.BoolValue" => "bool?",
            "google.protobuf.Int32Value" => "int?",
            "google.protobuf.Int64Value" => "long?",
            "google.protobuf.UInt32Value" => "uint?",
            "google.protobuf.UInt64Value" => "ulong?",
            "google.protobuf.FloatValue" => "float?",
            "google.protobuf.DoubleValue" => "double?",
            "google.protobuf.StringValue" => "string?",
            "google.protobuf.BytesValue" => "byte[]?",
            _ => null,
        };
    }

    private static string BuildProtoMapArgs(string? keyDataFormat, string? valueDataFormat)
    {
        var parts = new List<string>();
        if (keyDataFormat != null)
            parts.Add($"KeyFormat = global::LightProto.{keyDataFormat}");
        if (valueDataFormat != null)
            parts.Add($"ValueFormat = global::LightProto.{valueDataFormat}");
        return string.Join(", ", parts);
    }

    // -------------------------------------------------------------------------
    // Map-entry lookup: build a flat dictionary of ".MsgName.EntryName" -> DescriptorProto
    // -------------------------------------------------------------------------

    private static Dictionary<string, DescriptorProto> BuildMapEntryLookup(IList<DescriptorProto> messages, string prefix = "")
    {
        var result = new Dictionary<string, DescriptorProto>();
        foreach (var msg in messages)
        {
            var msgKey = $"{prefix}.{msg.Name}";
            foreach (var nested in msg.NestedTypes)
            {
                if (nested.Options?.MapEntry == true)
                    result[$"{msgKey}.{nested.Name}"] = nested;
            }
            // Recurse into nested messages
            var deeper = BuildMapEntryLookup(msg.NestedTypes, msgKey);
            foreach (var kvp in deeper)
                result[kvp.Key] = kvp.Value;
        }
        return result;
    }

    // -------------------------------------------------------------------------
    // Name conversion utilities
    // -------------------------------------------------------------------------

    /// <summary>
    /// Converts snake_case or ALL_CAPS to PascalCase.
    /// </summary>
    internal static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "Generated";

        // If there are no underscores and the name is not all-uppercase,
        // just ensure the first character is upper-cased and leave the rest as-is
        // (this preserves existing PascalCase / camelCase type and field names).
        bool hasUnderscore = name.Contains('_');
        bool isAllUpper = !hasUnderscore && name.All(c => !char.IsLetter(c) || char.IsUpper(c));

        if (!hasUnderscore && !isAllUpper)
            return name.Length == 1 ? char.ToUpperInvariant(name[0]).ToString() : char.ToUpperInvariant(name[0]) + name[1..];

        // For snake_case, ALL_CAPS, or ALL_CAPS_WITH_UNDERSCORES:
        // split on underscores and title-case each segment.
        var parts = name.Split('_');
        var sb = new System.Text.StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0)
                continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part[1..].ToLowerInvariant());
        }

        // If all parts were empty (e.g., name is only underscores), fall back to a safe default.
        return sb.Length == 0 ? "Generated" : sb.ToString();
    }
}
