using Google.Protobuf.Reflection;
using ProtoBuf.Reflection;

namespace LightProto.ProtoGen;

/// <summary>
/// Generates LightProto [ProtoContract] C# classes from a parsed proto FileDescriptorSet.
/// </summary>
internal sealed class LightProtoCSharpGenerator
{
    // Maps proto scalar types to their C# type names and optional DataFormat
    private static readonly Dictionary<FieldDescriptorProto.Type, (string CsType, string? DataFormat)> ScalarTypeMap = new()
    {
        [FieldDescriptorProto.Type.TypeDouble] = ("double", null),
        [FieldDescriptorProto.Type.TypeFloat] = ("float", null),
        [FieldDescriptorProto.Type.TypeInt32] = ("int", null),
        [FieldDescriptorProto.Type.TypeInt64] = ("long", null),
        [FieldDescriptorProto.Type.TypeUint32] = ("uint", null),
        [FieldDescriptorProto.Type.TypeUint64] = ("ulong", null),
        [FieldDescriptorProto.Type.TypeSint32] = ("int", "DataFormat.ZigZag"),
        [FieldDescriptorProto.Type.TypeSint64] = ("long", "DataFormat.ZigZag"),
        [FieldDescriptorProto.Type.TypeFixed32] = ("uint", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeFixed64] = ("ulong", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeSfixed32] = ("int", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeSfixed64] = ("long", "DataFormat.FixedSize"),
        [FieldDescriptorProto.Type.TypeBool] = ("bool", null),
        [FieldDescriptorProto.Type.TypeString] = ("string", null),
        [FieldDescriptorProto.Type.TypeBytes] = ("byte[]", null),
    };

    private readonly string _indent = "    ";

    /// <summary>
    /// Generates C# source code for all messages and enums in the given file descriptor.
    /// </summary>
    public string Generate(FileDescriptorProto file, string? overrideNamespace = null)
    {
        var ns =
            overrideNamespace ?? file.Options?.CsharpNamespace ?? ToPascalCase(Path.GetFileNameWithoutExtension(file.Name ?? "Generated"));

        // Build a lookup of all map-entry nested types for the whole file
        var mapEntries = BuildMapEntryLookup(file.MessageTypes);

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file was generated by lightproto-gen. Do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");

        bool firstItem = true;

        // Top-level enums
        foreach (var enumType in file.EnumTypes)
        {
            if (!firstItem)
                sb.AppendLine();
            firstItem = false;
            AppendEnum(sb, enumType, _indent);
        }

        // Top-level messages
        foreach (var message in file.MessageTypes)
        {
            if (!firstItem)
                sb.AppendLine();
            firstItem = false;
            AppendMessage(sb, message, mapEntries, _indent);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Enum generation
    // -------------------------------------------------------------------------

    private static void AppendEnum(System.Text.StringBuilder sb, EnumDescriptorProto enumType, string indent)
    {
        sb.AppendLine($"{indent}public enum {ToPascalCase(enumType.Name)}");
        sb.AppendLine($"{indent}{{");
        foreach (var value in enumType.Values)
        {
            sb.AppendLine($"{indent}    {ToPascalCase(value.Name)} = {value.Number},");
        }
        sb.AppendLine($"{indent}}}");
    }

    // -------------------------------------------------------------------------
    // Message generation
    // -------------------------------------------------------------------------

    private void AppendMessage(
        System.Text.StringBuilder sb,
        DescriptorProto message,
        Dictionary<string, DescriptorProto> mapEntries,
        string indent
    )
    {
        // Skip map-entry synthetic messages (they are handled inline as Dictionary<K,V>)
        if (message.Options?.MapEntry == true)
            return;

        // Add nested map entries from this message to the lookup
        var localMapEntries = new Dictionary<string, DescriptorProto>(mapEntries);
        foreach (var nested in message.NestedTypes)
        {
            if (nested.Options?.MapEntry == true)
                localMapEntries[$".{message.Name}.{nested.Name}"] = nested;
        }

        sb.AppendLine($"{indent}[global::LightProto.ProtoContract]");
        sb.AppendLine($"{indent}public partial class {ToPascalCase(message.Name)}");
        sb.AppendLine($"{indent}{{");

        var innerIndent = indent + _indent;

        // Nested enums
        foreach (var enumType in message.EnumTypes)
        {
            AppendEnum(sb, enumType, innerIndent);
            sb.AppendLine();
        }

        // Nested messages (non-map-entry)
        foreach (var nested in message.NestedTypes)
        {
            if (nested.Options?.MapEntry == true)
                continue;
            AppendMessage(sb, nested, localMapEntries, innerIndent);
            sb.AppendLine();
        }

        // Fields
        bool firstField = true;
        foreach (var field in message.Fields)
        {
            if (!firstField)
                sb.AppendLine();
            firstField = false;
            AppendField(sb, field, localMapEntries, innerIndent);
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void AppendField(
        System.Text.StringBuilder sb,
        FieldDescriptorProto field,
        Dictionary<string, DescriptorProto> mapEntries,
        string indent
    )
    {
        // Detect map fields: repeated message whose type is a map-entry
        if (
            field.label == FieldDescriptorProto.Label.LabelRepeated
            && field.type == FieldDescriptorProto.Type.TypeMessage
            && mapEntries.TryGetValue(field.TypeName, out var mapEntry)
        )
        {
            AppendMapField(sb, field, mapEntry, indent);
            return;
        }

        bool isRepeated = field.label == FieldDescriptorProto.Label.LabelRepeated;
        var (csType, dataFormat) = ResolveType(field, mapEntries);

        // Build [ProtoMember] attribute
        var memberAttrArgs = $"{field.Number}";
        if (dataFormat != null)
            memberAttrArgs += $", DataFormat = global::LightProto.{dataFormat}";

        sb.AppendLine($"{indent}[global::LightProto.ProtoMember({memberAttrArgs})]");

        if (isRepeated)
        {
            sb.AppendLine(
                $"{indent}public global::System.Collections.Generic.List<{csType}> {ToPascalCase(field.Name)} {{ get; set; }} = new();"
            );
        }
        else if (csType == "string")
        {
            sb.AppendLine($"{indent}public string {ToPascalCase(field.Name)} {{ get; set; }} = string.Empty;");
        }
        else if (csType == "byte[]")
        {
            sb.AppendLine($"{indent}public byte[] {ToPascalCase(field.Name)} {{ get; set; }} = global::System.Array.Empty<byte>();");
        }
        else if (IsScalarValueType(field.type))
        {
            sb.AppendLine($"{indent}public {csType} {ToPascalCase(field.Name)} {{ get; set; }}");
        }
        else
        {
            // Message or enum reference - nullable for messages, value type for enums
            var isEnum = field.type == FieldDescriptorProto.Type.TypeEnum;
            if (isEnum)
                sb.AppendLine($"{indent}public {csType} {ToPascalCase(field.Name)} {{ get; set; }}");
            else
                sb.AppendLine($"{indent}public {csType}? {ToPascalCase(field.Name)} {{ get; set; }}");
        }
    }

    private static void AppendMapField(System.Text.StringBuilder sb, FieldDescriptorProto field, DescriptorProto mapEntry, string indent)
    {
        var keyField = mapEntry.Fields.First(f => f.Name == "key");
        var valueField = mapEntry.Fields.First(f => f.Name == "value");

        var (keyCs, keyDataFormat) = ResolveType(keyField, new Dictionary<string, DescriptorProto>());
        var (valueCs, valueDataFormat) = ResolveType(valueField, new Dictionary<string, DescriptorProto>());

        // Build [ProtoMember] + [ProtoMap]
        sb.AppendLine($"{indent}[global::LightProto.ProtoMember({field.Number})]");
        var protoMapArgs = BuildProtoMapArgs(keyDataFormat, valueDataFormat);
        if (protoMapArgs.Length > 0)
            sb.AppendLine($"{indent}[global::LightProto.ProtoMap({protoMapArgs})]");
        else
            sb.AppendLine($"{indent}[global::LightProto.ProtoMap]");

        sb.AppendLine(
            $"{indent}public global::System.Collections.Generic.Dictionary<{keyCs}, {valueCs}> {ToPascalCase(field.Name)} {{ get; set; }} = new();"
        );
    }

    // -------------------------------------------------------------------------
    // Type resolution helpers
    // -------------------------------------------------------------------------

    private static (string CsType, string? DataFormat) ResolveType(
        FieldDescriptorProto field,
        Dictionary<string, DescriptorProto> mapEntries
    )
    {
        if (ScalarTypeMap.TryGetValue(field.type, out var scalar))
            return scalar;

        if (field.type == FieldDescriptorProto.Type.TypeEnum || field.type == FieldDescriptorProto.Type.TypeMessage)
        {
            // TypeName is like ".pkg.TypeName" or ".OuterMessage.InnerType"
            var typeName = field.TypeName?.TrimStart('.') ?? "object";

            // For well-known types, map to C# equivalents first
            var wellKnown = MapWellKnownType(typeName);
            if (wellKnown is not null)
                return (wellKnown, null);

            // Apply PascalCase to each dotted segment so generated class names match
            var csName = string.Join(".", typeName.Split('.').Select(ToPascalCase));
            return (csName, null);
        }

        return ("object", null);
    }

    private static string? MapWellKnownType(string protoTypeName)
    {
        return protoTypeName switch
        {
            "google.protobuf.Timestamp" => "global::System.DateTime",
            "google.protobuf.Duration" => "global::System.TimeSpan",
            "google.protobuf.BoolValue" => "bool?",
            "google.protobuf.Int32Value" => "int?",
            "google.protobuf.Int64Value" => "long?",
            "google.protobuf.UInt32Value" => "uint?",
            "google.protobuf.UInt64Value" => "ulong?",
            "google.protobuf.FloatValue" => "float?",
            "google.protobuf.DoubleValue" => "double?",
            "google.protobuf.StringValue" => "string?",
            "google.protobuf.BytesValue" => "byte[]?",
            _ => null,
        };
    }

    private static bool IsScalarValueType(FieldDescriptorProto.Type type)
    {
        return type switch
        {
            FieldDescriptorProto.Type.TypeDouble => true,
            FieldDescriptorProto.Type.TypeFloat => true,
            FieldDescriptorProto.Type.TypeInt32 => true,
            FieldDescriptorProto.Type.TypeInt64 => true,
            FieldDescriptorProto.Type.TypeUint32 => true,
            FieldDescriptorProto.Type.TypeUint64 => true,
            FieldDescriptorProto.Type.TypeSint32 => true,
            FieldDescriptorProto.Type.TypeSint64 => true,
            FieldDescriptorProto.Type.TypeFixed32 => true,
            FieldDescriptorProto.Type.TypeFixed64 => true,
            FieldDescriptorProto.Type.TypeSfixed32 => true,
            FieldDescriptorProto.Type.TypeSfixed64 => true,
            FieldDescriptorProto.Type.TypeBool => true,
            _ => false,
        };
    }

    private static string BuildProtoMapArgs(string? keyDataFormat, string? valueDataFormat)
    {
        var parts = new List<string>();
        if (keyDataFormat != null)
            parts.Add($"KeyFormat = global::LightProto.{keyDataFormat}");
        if (valueDataFormat != null)
            parts.Add($"ValueFormat = global::LightProto.{valueDataFormat}");
        return string.Join(", ", parts);
    }

    // -------------------------------------------------------------------------
    // Map-entry lookup: build a flat dictionary of ".MsgName.EntryName" -> DescriptorProto
    // -------------------------------------------------------------------------

    private static Dictionary<string, DescriptorProto> BuildMapEntryLookup(IList<DescriptorProto> messages, string prefix = "")
    {
        var result = new Dictionary<string, DescriptorProto>();
        foreach (var msg in messages)
        {
            var msgKey = $"{prefix}.{msg.Name}";
            foreach (var nested in msg.NestedTypes)
            {
                if (nested.Options?.MapEntry == true)
                    result[$"{msgKey}.{nested.Name}"] = nested;
            }
            // Recurse into nested messages
            var deeper = BuildMapEntryLookup(msg.NestedTypes, msgKey);
            foreach (var kvp in deeper)
                result[kvp.Key] = kvp.Value;
        }
        return result;
    }

    // -------------------------------------------------------------------------
    // Name conversion utilities
    // -------------------------------------------------------------------------

    /// <summary>
    /// Converts snake_case or ALL_CAPS to PascalCase.
    /// </summary>
    internal static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "Generated";

        // If there are no underscores and the name is not all-uppercase,
        // just ensure the first character is upper-cased and leave the rest as-is
        // (this preserves existing PascalCase / camelCase type and field names).
        bool hasUnderscore = name.Contains('_');
        bool isAllUpper = !hasUnderscore && name.All(c => !char.IsLetter(c) || char.IsUpper(c));

        if (!hasUnderscore && !isAllUpper)
            return char.ToUpperInvariant(name[0]) + name[1..];

        // For snake_case, ALL_CAPS, or ALL_CAPS_WITH_UNDERSCORES:
        // split on underscores and title-case each segment.
        var parts = name.Split('_');
        var sb = new System.Text.StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0)
                continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part[1..].ToLowerInvariant());
        }

        // If all parts were empty (e.g., name is only underscores), fall back to a safe default.
        return sb.Length == 0 ? "Generated" : sb.ToString();
    }
}
