// <auto-generated/>
#pragma warning disable
file static class DisableReflectionScanner_dc1ff454f9b74254ace657fb5dfc5407
{
	[global::System.Runtime.CompilerServices.ModuleInitializer]
	public static void Initialize()
	{
		global::TUnit.Core.SourceRegistrar.IsEnabled = true;
	}
}
